// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdEs6hG8suSbz1CM2vElADtmL1ueqHr2g',
    appId: '1:827307194573:web:bf65f371ef9cba401a5184',
    messagingSenderId: '827307194573',
    projectId: 'van-tracking-app-168bf',
    authDomain: 'van-tracking-app-168bf.firebaseapp.com',
    storageBucket: 'van-tracking-app-168bf.firebasestorage.app',
    measurementId: 'G-PH0222P00X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7-PGHHHRbVPBrVVQ-to3YsaAedFJWIoo',
    appId: '1:827307194573:android:dab06d04cbcf6fa71a5184',
    messagingSenderId: '827307194573',
    projectId: 'van-tracking-app-168bf',
    storageBucket: 'van-tracking-app-168bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmdLwDeaj9GsW3_ahj6Nb7oktVASnX7ic',
    appId: '1:827307194573:ios:4425b62caafe7fac1a5184',
    messagingSenderId: '827307194573',
    projectId: 'van-tracking-app-168bf',
    storageBucket: 'van-tracking-app-168bf.firebasestorage.app',
    iosBundleId: 'com.example.schoolVan',
  );
}
